### ISSUE TITLE
Dev 模式运行微信小程序，一段时间后会自动结束

### ISSUE THREAD

**Issue by maxoyed** [uni-helper/vitesse-uni-app#17]
### Describe the bug

```bash
DONE  Build complete. Watching for changes...
开始差量编译...
DONE  Build complete. Watching for changes...
开始差量编译...
DONE  Build complete. Watching for changes...
开始差量编译...
DONE  Build complete. Watching for changes...
node:events:495
      throw er; // Unhandled 'error' event
      ^

Error: EBUSY: resource busy or locked, lstat 'G:\DumpStack.log.tmp'
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (file:///G:/project/other/uni-vite-ts/node_modules/.pnpm/rollup@3.27.2/node_modules/rollup/dist/es/shared/watch.js:4246:10)
    at NodeFsHandler._boundHandleError (file:///G:/project/other/uni-vite-ts/node_modules/.pnpm/rollup@3.27.2/node_modules/rollup/dist/es/shared/watch.js:2720:43)
    at ReaddirpStream.emit (node:events:517:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4082,
  code: 'EBUSY',
  syscall: 'lstat',
  path: 'G:\\DumpStack.log.tmp'
}

Node.js v18.18.0
 ELIFECYCLE  Command failed with exit code 1.
```

### Reproduction

```bash
npx degit uni-helper/vitesse-uni-app uni-vite-ts
cd uni-vite-ts && pnpm i
pnpm run dev:mp-weixin
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12400F
    Memory: 4.67 GB / 15.76 GB
  Binaries:
    Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.6 - G:\project\other\node_modules\.bin\npm.CMD
    pnpm: 8.7.6 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.2283.0), Chromium (117.0.2045.36)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by KeJunMao** [comment]
参考 https://github.com/uni-helper/vitesse-uni-app/pull/9
